# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from koa.grpc import KiwoomOpenApiService_pb2 as koa_dot_grpc_dot_KiwoomOpenApiService__pb2


class KiwoomOpenApiServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/koa.grpc.KiwoomOpenApiService/Call',
                request_serializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CallRequest.SerializeToString,
                response_deserializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CallResponse.FromString,
                )
        self.Listen = channel.unary_stream(
                '/koa.grpc.KiwoomOpenApiService/Listen',
                request_serializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.ListenRequest.SerializeToString,
                response_deserializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomListenResponse.FromString,
                )
        self.StopListen = channel.unary_unary(
                '/koa.grpc.KiwoomOpenApiService/StopListen',
                request_serializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.StopListenRequest.SerializeToString,
                response_deserializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.StopListenResponse.FromString,
                )
        self.CustomListen = channel.unary_stream(
                '/koa.grpc.KiwoomOpenApiService/CustomListen',
                request_serializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomListenRequest.SerializeToString,
                response_deserializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomListenResponse.FromString,
                )
        self.CustomCallAndListen = channel.unary_stream(
                '/koa.grpc.KiwoomOpenApiService/CustomCallAndListen',
                request_serializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomCallAndListenRequest.SerializeToString,
                response_deserializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomCallAndListenResponse.FromString,
                )
        self.LoginCall = channel.unary_stream(
                '/koa.grpc.KiwoomOpenApiService/LoginCall',
                request_serializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.LoginRequest.SerializeToString,
                response_deserializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomCallAndListenResponse.FromString,
                )
        self.TransactionCall = channel.unary_stream(
                '/koa.grpc.KiwoomOpenApiService/TransactionCall',
                request_serializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.TransactionRequest.SerializeToString,
                response_deserializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomCallAndListenResponse.FromString,
                )
        self.OrderCall = channel.unary_stream(
                '/koa.grpc.KiwoomOpenApiService/OrderCall',
                request_serializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.OrderRequest.SerializeToString,
                response_deserializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomCallAndListenResponse.FromString,
                )
        self.RealCall = channel.unary_stream(
                '/koa.grpc.KiwoomOpenApiService/RealCall',
                request_serializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.RealRequest.SerializeToString,
                response_deserializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomCallAndListenResponse.FromString,
                )


class KiwoomOpenApiServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Listen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopListen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CustomListen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CustomCallAndListen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransactionCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OrderCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RealCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KiwoomOpenApiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CallRequest.FromString,
                    response_serializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CallResponse.SerializeToString,
            ),
            'Listen': grpc.unary_stream_rpc_method_handler(
                    servicer.Listen,
                    request_deserializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.ListenRequest.FromString,
                    response_serializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomListenResponse.SerializeToString,
            ),
            'StopListen': grpc.unary_unary_rpc_method_handler(
                    servicer.StopListen,
                    request_deserializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.StopListenRequest.FromString,
                    response_serializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.StopListenResponse.SerializeToString,
            ),
            'CustomListen': grpc.unary_stream_rpc_method_handler(
                    servicer.CustomListen,
                    request_deserializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomListenRequest.FromString,
                    response_serializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomListenResponse.SerializeToString,
            ),
            'CustomCallAndListen': grpc.unary_stream_rpc_method_handler(
                    servicer.CustomCallAndListen,
                    request_deserializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomCallAndListenRequest.FromString,
                    response_serializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomCallAndListenResponse.SerializeToString,
            ),
            'LoginCall': grpc.unary_stream_rpc_method_handler(
                    servicer.LoginCall,
                    request_deserializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.LoginRequest.FromString,
                    response_serializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomCallAndListenResponse.SerializeToString,
            ),
            'TransactionCall': grpc.unary_stream_rpc_method_handler(
                    servicer.TransactionCall,
                    request_deserializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.TransactionRequest.FromString,
                    response_serializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomCallAndListenResponse.SerializeToString,
            ),
            'OrderCall': grpc.unary_stream_rpc_method_handler(
                    servicer.OrderCall,
                    request_deserializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.OrderRequest.FromString,
                    response_serializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomCallAndListenResponse.SerializeToString,
            ),
            'RealCall': grpc.unary_stream_rpc_method_handler(
                    servicer.RealCall,
                    request_deserializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.RealRequest.FromString,
                    response_serializer=koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomCallAndListenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'koa.grpc.KiwoomOpenApiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KiwoomOpenApiService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/koa.grpc.KiwoomOpenApiService/Call',
            koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CallRequest.SerializeToString,
            koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CallResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Listen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/koa.grpc.KiwoomOpenApiService/Listen',
            koa_dot_grpc_dot_KiwoomOpenApiService__pb2.ListenRequest.SerializeToString,
            koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomListenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopListen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/koa.grpc.KiwoomOpenApiService/StopListen',
            koa_dot_grpc_dot_KiwoomOpenApiService__pb2.StopListenRequest.SerializeToString,
            koa_dot_grpc_dot_KiwoomOpenApiService__pb2.StopListenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CustomListen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/koa.grpc.KiwoomOpenApiService/CustomListen',
            koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomListenRequest.SerializeToString,
            koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomListenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CustomCallAndListen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/koa.grpc.KiwoomOpenApiService/CustomCallAndListen',
            koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomCallAndListenRequest.SerializeToString,
            koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomCallAndListenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoginCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/koa.grpc.KiwoomOpenApiService/LoginCall',
            koa_dot_grpc_dot_KiwoomOpenApiService__pb2.LoginRequest.SerializeToString,
            koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomCallAndListenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TransactionCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/koa.grpc.KiwoomOpenApiService/TransactionCall',
            koa_dot_grpc_dot_KiwoomOpenApiService__pb2.TransactionRequest.SerializeToString,
            koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomCallAndListenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OrderCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/koa.grpc.KiwoomOpenApiService/OrderCall',
            koa_dot_grpc_dot_KiwoomOpenApiService__pb2.OrderRequest.SerializeToString,
            koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomCallAndListenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RealCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/koa.grpc.KiwoomOpenApiService/RealCall',
            koa_dot_grpc_dot_KiwoomOpenApiService__pb2.RealRequest.SerializeToString,
            koa_dot_grpc_dot_KiwoomOpenApiService__pb2.CustomCallAndListenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
